language: go
sudo: false
go:
  - 1.4

addons:
  apt:
    packages:
    - libpcap-dev

install: 
  - go clean -i net
  - go install -tags netgo std
  - make travis

script:
  - make tests

after_success:
  - go get github.com/mattn/goveralls
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
